version: 0.2


phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - python --version
      - aws --version
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - echo "this is to test build gets triggered or not"
      #- docker build -t lsmtest:latest .
      - aws --version
      - ls -la
      - pwd
      - cd deployment/assets/model_local/
      - pwd
      - ls -la
      - echo "${PWD}"
      - docker build -t lsmtest:latest .
      - docker run -v $PWD:/modeldata lsmtest:latest
      - ls -la
      - pwd
      - aws --version
      
artifacts:
    files: imagedefinitions.json