version: 0.2


phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - python --version
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - echo "this is to test build gets triggered or not"
      - docker build -t lsmtest:latest .
artifacts:
    files: imagedefinitions.json