name: base
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.9.12
  - pandas==1.4.2
  - numpy
  - pip
  - pip:
    - annoy==1.17.0
    - anytree==2.8.0
    - sentence-transformers==2.2.0
